baseURL = "/"
languageCode = "it-it"
defaultContentLanguage = "it"
title = "Osservatorio su Parlamento e Corti"
theme = "arcana"

[params]
  description = "Osservatorio su Parlamento e Corti dell'Università di Catania"
  copyright = "© Osservatorio su Parlamento e Corti. Tutti i diritti riservati."
  mainSections = ["in-evidenza", "legislazione", "corti", "news"]
  images = ["images/logo.jpg"]
  mailchimpURL = "https://example.us1.list-manage.com/subscribe/post?u=FAKE_U&amp;id=FAKE_ID"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Il Progetto"
    url = "/il-progetto/"
    weight = 2
  [[menu.main]]
    name = "Redazione"
    url = "/redazione/"
    weight = 3
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 4
  [[menu.main]]
    name = "Archivio"
    url = "/archivio/"
    weight = 5
  [[menu.main]]
    name = "Link Utili"
    url = "/link-utili/"
    weight = 6

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*'] 