backend:
  name: git-gateway
  branch: main
  squash_merges: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

locale: 'it'

collections:
  - name: "dottrina"
    label: "Dottrina"
    folder: "content/dottrina"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: &contentFields
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data di pubblicazione", name: "date", widget: "datetime"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Immagine in evidenza", name: "featured_image", widget: "image"}
      - {label: "PDF associato", name: "pdf", widget: "file", required: false}
      - {label: "Categorie", name: "categories", widget: "list"}
      - {label: "Corpo", name: "body", widget: "markdown"}

  - name: "documentazione"
    label: "Documentazione"
    folder: "content/documentazione"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: *contentFields

  - name: "legislazione"
    label: "Legislazione"
    folder: "content/legislazione"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: *contentFields

  - name: "giurisprudenza"
    label: "Giurisprudenza"
    folder: "content/giurisprudenza"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: *contentFields

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: *contentFields

  - name: "settings"
    label: "Impostazioni"
    files:
      - name: "footer"
        label: "Footer"
        file: "data/footer.yml"
        fields:
          - label: "Logo Contatti"
            name: "contact_logo"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Immagine", name: "image", widget: "image"}
              - {label: "Testo alternativo", name: "alt", widget: "string"}
          
          - label: "Informazioni di Contatto"
            name: "contact_info"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Dipartimento", name: "department", widget: "string"}
              - {label: "Indirizzo", name: "address", widget: "string"}
              - label: "Email"
                name: "email"
                widget: "object"
                fields:
                  - {label: "Redazione", name: "editorial", widget: "string"}
                  - {label: "News", name: "news", widget: "string"}
          
          - label: "Privacy"
            name: "privacy"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Testo", name: "text", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
          
          - label: "Area Riservata"
            name: "admin_area"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Testo", name: "text", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}

  - name: "pages"
    label: "Pagine"
    files:
      - name: "chi-siamo"
        label: "Chi Siamo"
        file: "content/chi-siamo/_index.md"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Contenuto", name: "body", widget: "markdown"}
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"} 
      
      - name: "link-utili"
        label: "Link Utili"
        file: "content/link-utili/_index.md"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - label: "Riviste Scientifiche"
            name: "riviste"
            widget: "list"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
          - label: "Siti Istituzionali"
            name: "istituzioni"
            widget: "list"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"} 