backend:
  name: git-gateway
  branch: main
  squash_merges: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

locale: 'it'

collections:
  - name: "dottrina"
    label: "Dottrina"
    folder: "content/dottrina"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data di pubblicazione", name: "date", widget: "datetime"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Immagine in evidenza", name: "featured_image", widget: "image"}
      - {label: "Categorie", name: "categories", widget: "list"}
      - {label: "Corpo", name: "body", widget: "markdown"}

  - name: "documentazione"
    label: "Documentazione"
    folder: "content/documentazione"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data di pubblicazione", name: "date", widget: "datetime"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Immagine in evidenza", name: "featured_image", widget: "image"}
      - {label: "Categorie", name: "categories", widget: "list"}
      - {label: "Corpo", name: "body", widget: "markdown"}

  - name: "legislazione"
    label: "Legislazione"
    folder: "content/legislazione"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data di pubblicazione", name: "date", widget: "datetime"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Immagine in evidenza", name: "featured_image", widget: "image"}
      - {label: "Categorie", name: "categories", widget: "list"}
      - {label: "Corpo", name: "body", widget: "markdown"}

  - name: "giurisprudenza"
    label: "Giurisprudenza"
    folder: "content/giurisprudenza"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data di pubblicazione", name: "date", widget: "datetime"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Immagine in evidenza", name: "featured_image", widget: "image"}
      - {label: "Categorie", name: "categories", widget: "list"}
      - {label: "Corpo", name: "body", widget: "markdown"}

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data di pubblicazione", name: "date", widget: "datetime"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Immagine in evidenza", name: "featured_image", widget: "image"}
      - {label: "Categorie", name: "categories", widget: "list"}
      - {label: "Corpo", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pagine"
    files:
      - name: "chi-siamo"
        label: "Chi Siamo"
        file: "content/chi-siamo/_index.md"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Immagine", name: "image", widget: "image"}
          - {label: "Contenuto", name: "body", widget: "markdown"}
      
      - name: "link-utili"
        label: "Link Utili"
        file: "content/link-utili/_index.md"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - label: "Riviste Scientifiche"
            name: "riviste"
            widget: "list"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
          - label: "Siti Istituzionali"
            name: "istituzioni"
            widget: "list"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"} 